language: node_js
node_js:
- "7"
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
script:
- ng build --prod --aot
deploy:
provider: firebase
  token:
    secure: "hrk0OVxuMU5Z0hDpZVBaBX3m0lMpELN0hkK25kSRcmmkXpxurPaOmS2EmGhcb+pSJybNLCkIYZaRSgEiXeqNgHADKXZBJPuXIyxKIyK4gGbl7mFtx1VUmKwYFY1oQW92RO8oVxl12Q11QVFnxzt1980NoajRKgpFFz+kxyluct85JveCwEjXhGHEfciEYcjmu02wb82qaljzejOBtOXlceTEGbL2G22ea/JZjuF4DoQRRCb00enT8KjS0YQFxXCRbItEB0no9oATqKA8WCLkaPjrWMffbPkscPFFUFZk4hnCV+bcJ9j/+pr+/7QCW8ABROACxEtTWShHuoev+ojUalKAGdTQD0GwNLxF9UHLx3vms3wJeLjHl3eQCZpv6eDB6uKEFPVMZL0EZHoSWTn49MP2sL3RX8ol4yeSVcvlOLNXZmGy5+qYGpMlfjxjmaMkTpkVMiyg8Sj/Ha+TMLUVPqs9YMXSwy4upguDCqmMnxF7vquqiASFZSZFShqahqXmj4JUdRAU+6bACJmdo0HBYHJcXdSY9sA0+caCKDxqggPoyFFPvfY5WoBm4XTt0SgYewk0aoP94VPZpN7rdfwvPtu+fHiGdIxOb3M+nfWP0B33yjwZcHf6DYvm5Rm2WPgExx1q3KouA4ZJzSAvT0FjS5azeQlmSucIIOxtkBUTrzM="
  project: "algosanddatastructures-3acf6"
