language: node_js
node_js:
- '8'
branches:
  only:
  - master
before_script:
- npm install -g firebase-tools
- npm install -g @angular/cli
- npm install -g tslint
- npm install -g typescript
script:
- npm run env -s && ng build --prod --aot
after_success:
- cd functions && npm install && cd -
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN_SECURE
  project: algosanddatastructures-3acf6
