// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  version: env.npm_package_version,
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: [
    'en-US',
    'fr-FR'
  ],
  firebase: {
    apiKey: "AIzaSyBruCY0Sl4VIZCS5YpEJcslLYWhXGzlgtc",
    authDomain: "algosanddatastructures-3acf6.firebaseapp.com",
    databaseURL: "https://algosanddatastructures-3acf6.firebaseio.com",
    projectId: "algosanddatastructures-3acf6",
    storageBucket: "algosanddatastructures-3acf6.appspot.com",
    messagingSenderId: "266099261743"
  },
  algolia: {
    appId: "N1YAJ7U0GZ",
    searchKey: "d2d1df3ba0ab7610a49b3c24808fbdd5",
    indexName: "data"
  }
};
